apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leases-access
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["backup.test.io"]
  resources: ["backupdatabaseschemas"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["backup.test.io"]
  resources: ["backupdatabaseschemas/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]

