apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-manager-leases-access
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
roleRef:
  kind: ClusterRole
  name: leases-access
  apiGroup: rbac.authorization.k8s.io
