# This rule is not used by the project test-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the backup.test.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test-crd
    app.kubernetes.io/managed-by: kustomize
  name: backupdatabaseschema-editor-role
rules:
- apiGroups:
  - backup.test.io
  resources:
  - backupdatabaseschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.test.io
  resources:
  - backupdatabaseschemas/status
  verbs:
  - get
