apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret-docker
    namespace: system
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CGiSbjkI/1A4Ff7VqNhBcUMgPri5YIxSPaJIQAjulOe9Pkxc2MRnh7UOPgX4+34oli3X0HShQCqWLBcyPJwGxvGgerbTK4Z2C1tTqA1P92poyeHa6fk9XzqBtirz1xschyZcCJdW2OC+SehQJaslIkwLLp0mgYXdBxjv3xleD5RFdhmWLKqHSvAO7ZXpycYPTWU3gW07Z9ZGOoCVZzJuFALuIc3EV61h8nwO9s9g+JkQn8VmLplo2nr3Orvv76wnSeeTRjzfB24rjLXNU/60S73ahczUC+CL4ndo1mFXzexrDzLXjHZi5sKRlCV/rgl/56mRaRyV9X+jpCTQusNW/866iUhEkFbBtGawj7ivXRCWhFkO3HxI+KLLTkgVSYHhRCOayx1kEwkHUFoBdaf5li8+asHCc6hJRrsuv7wVD5I=,iv:miWh+tcodafgcvt49Zc1Ffj5jxmhCWIjBP5eFhUy8bk=,tag:52CrqViDRjUU5A0wcMrMOQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:418295703729:key/e632f6ac-2567-4d4d-870b-ff6a140c6188
          created_at: "2025-03-20T16:37:47Z"
          enc: AQICAHi7oh61ZlQ7I3LrLWwkvps7Q9v67DixnZ8669gi5wSszgHagbaPVRSVcyNDqz5+e1DKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJG4Nsh6GTUQqXlq8AgEQgDvnvIc60TpR4Rlwm4fIVJk9/UPFyjuS2qpm1zzRqwZ4upFo04zeNqmUSQaQaDFbU/teiJJ1L5/ZCvA4JA==
          aws_profile: csye7125-root
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-20T16:37:47Z"
    mac: ENC[AES256_GCM,data:YfF90Fwxj2d1zN8NX0qDVxPjpTvmrAi7gKjmFCmEv1xwDr3kPTKKFiupcdcXjnpUkW6/qexZeqwfjt/ViAmbZk+38uoya873nU0jTButSwfz8+U552UY/rYlGrWQbS86lYcx58vO8Tt+ln0rjZ/9hVYlO4CiW0yYSLQbd0E1czo=,iv:pvgFI5XMhYG8yK++Bhe2G3g38dt0R/G0x3gGdsbPs7g=,tag:yPLVgx3NVi3nq45NXFHTJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: database-secrets
    namespace: backup
type: Opaque
data:
    DB_USERNAME: ENC[AES256_GCM,data:aOawiLp/zj4=,iv:IsWFdfZzcShkGHnoO210qIdtg+FZ+Um5WPYSLs+e9CE=,tag:dgZEFVyMlKAYlSXlDWDx9w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:aHQSARirmwKPv5HQ,iv:w5IX4Ed+CW4hqmoi2s4edQ/sNNM2lJJEh6Z4LNovIgs=,tag:n6FCQp1iUUJ423bP5YxYuA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:418295703729:key/e632f6ac-2567-4d4d-870b-ff6a140c6188
          created_at: "2025-03-20T16:37:47Z"
          enc: AQICAHi7oh61ZlQ7I3LrLWwkvps7Q9v67DixnZ8669gi5wSszgHagbaPVRSVcyNDqz5+e1DKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJG4Nsh6GTUQqXlq8AgEQgDvnvIc60TpR4Rlwm4fIVJk9/UPFyjuS2qpm1zzRqwZ4upFo04zeNqmUSQaQaDFbU/teiJJ1L5/ZCvA4JA==
          aws_profile: csye7125-root
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-20T16:37:47Z"
    mac: ENC[AES256_GCM,data:YfF90Fwxj2d1zN8NX0qDVxPjpTvmrAi7gKjmFCmEv1xwDr3kPTKKFiupcdcXjnpUkW6/qexZeqwfjt/ViAmbZk+38uoya873nU0jTButSwfz8+U552UY/rYlGrWQbS86lYcx58vO8Tt+ln0rjZ/9hVYlO4CiW0yYSLQbd0E1czo=,iv:pvgFI5XMhYG8yK++Bhe2G3g38dt0R/G0x3gGdsbPs7g=,tag:yPLVgx3NVi3nq45NXFHTJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
